on:
  push:
    branches:
      - codeserver

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://quay.io/singularity/singularity:v3.9.4
      options: --privileged
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out code for the container builds
        uses: actions/checkout@v4
     
      - name: build
        run: |
          source ./retry.sh
          mkdir images
          export IMAGE_TAG=$(date +'%y%m%d%H%m')
          echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
        
          for def_file in container/base/*.def
          do
              b_name="$(basename $def_file .def)"
              if singularity build images/$b_name.sif $def_file; then
                retry 4 singularity push images/$b_name.sif oras://ghcr.io/${GITHUB_REPOSITORY}/$b_name:latest
                retry 4 singularity push images/$b_name.sif oras://ghcr.io/${GITHUB_REPOSITORY}/$b_name:$IMAGE_TAG
              fi
          done

          for def_file in container/dependent/*.def
          do
              b_name="$(basename $def_file .def)"
              if singularity build images/$b_name.sif $def_file; then
                retry 4 singularity push images/$b_name.sif oras://ghcr.io/${GITHUB_REPOSITORY}/$b_name:latest
                retry 4 singularity push images/$b_name.sif oras://ghcr.io/${GITHUB_REPOSITORY}/$b_name:$IMAGE_TAG
                rm images/$b_name.sif
              fi
          done
