on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://quay.io/singularity/singularity:v3.9.4
    steps:
      - name: Check out code for the container builds
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          mkdir images
          export IMAGE_TAG=$(date +'%y%m%d%H%m')
          export PYCHARM_VERSION=$(wget -qO- 'https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=pycharm-professional' | grep pkgver= | cut -d "=" -f2)
          echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
        
          for def_file in container/*.def
          do
              b_name="$(basename $def_file .def)"
              singularity build images/$b_name.sif $def_file
              singularity push images/$b_name.sif oras://ghcr.io/${GITHUB_REPOSITORY}/$b_name:latest
              singularity push images/$b_name.sif oras://ghcr.io/${GITHUB_REPOSITORY}/$b_name:$IMAGE_TAG
          done
