on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://quay.io/singularity/singularity:latest
    steps:
      - name: Build it
        run: echo "Hello"
