on:
  push:
    branches:
      - main
      - matlab_other
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: docker://quay.io/singularity/singularity:v4.1.0
      options: --privileged
    steps:
      - name: Check out code for the container builds
        uses: actions/checkout@v4

      - name: build
        run: |
          source ./retry.sh
          mkdir images
          export IMAGE_TAG=$(date +'%y%m%d%H%m')
          echo ${{ secrets.GITHUB_TOKEN }} | singularity registry login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
        
          for def_file in container/*.def
          do
              b_name="$(basename $def_file .def)"
              if singularity build images/$b_name.sif $def_file; then
                retry 4 singularity push images/$b_name.sif oras://ghcr.io/${GITHUB_REPOSITORY}/$b_name:latest
                retry 4 singularity push images/$b_name.sif oras://ghcr.io/${GITHUB_REPOSITORY}/$b_name:$IMAGE_TAG
              fi
          done
