on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://quay.io/singularity/singularity:v3.9.4
    steps:
      - name: Check out code for the container builds
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          mkdir images
        
          for def_file in container/*.def
          do
              b_name="$(basename $def_file .def)"
              singularity build images/$b_name.sif $def_file
          done
